### PR TITLE
Duration menu

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
This adds duration information to 2 possible locations in the Episode list:
* episode menu
* subtitle

Personally I think the subtitle option is better but I figured I would present both and get your opinions before remove one or the other...

Please note you need to add total_time in main.py of gpodder-ui-qml (https://github.com/gpodder/gpodder-ui-qml/pull/11)

Please also note I'm leaving both PRs (gpodder-core and gpodder-ui-qml) open for now and will roll 4.9 version number bumps into them before merging.
@carmenfdezb @sfbg

### CODE REVIEW

**Comment by carmenfdezb** [comment]
Hi @Keeper-of-the-Keys! I'm absolutely agree with you, I prefer duration in subtitle instead of episode menu

**Comment by carmenfdezb** [comment]
Hi @Keeper-of-the-Keys! I would like to add a little fix in gpodder before you release v4.9, is that possible?

**Comment by carmenfdezb** [comment]
When episode is paused, cover app doesn't show info about about episode (podcast and episode title, duration...). I think it is useful to see that info in cover, if an episode is loaded in player. What do you think?

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb Makes sense, is that a small change? I'd like to publish today...

**Comment by Keeper-of-the-Keys** [comment]
BTW I think for one of the future releases we need to look at a better way to do the qstrings for the translation file, I see in my diff that all kinds of strings are being deleted by qmake updating stuff (which is why I did not commit the updated translation files)

**Comment by carmenfdezb** [comment]
> 
> 
> @carmenfdezb Makes sense, is that a small change? I'd like to publish today...

Yes, it is a small change, I can do it when I come back home within 2 or 3 hours.

**Comment by carmenfdezb** [comment]
> 
> 
> BTW I think for one of the future releases we need to look at a better way to do the qstrings for the translation file, I see in my diff that all kinds of strings are being deleted by qmake updating stuff (which is why I did not commit the updated translation files)

I agree, I will take a look if you want, to solve it in the next release.

**Comment by Keeper-of-the-Keys** [comment]
OK, I'll merge this but wait for your PR with making a release

**Comment by carmenfdezb** [comment]
Done! Thank you!
#110

**Comment by carmenfdezb** [comment]
> BTW I think for one of the future releases we need to look at a better way to do the qstrings for the translation file, I see in my diff that all kinds of strings are being deleted by qmake updating stuff (which is why I did not commit the updated translation files)

Sorry, are you talking about changes in numbers line in the translation files?

**Comment by Keeper-of-the-Keys** [comment]
> Sorry, are you talking about changes in numbers line in the translation files?

From looking at one of the diffs it seemed that actual text was being lost... (ie being changed to unfinished and set to empty)

**Pull request merged**
