### PR TITLE
A file for the Bulgarian translation

### PR DESCRIPTION
**Pull request by sfbg**

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
Looking great!
Hopefully once Jolla passes the ownership on harbour we'll also add some more text among other things specifying who translated etc. so please stay tuned :)

**Comment by carmenfdezb** [comment]
Nice!! Thanks for translating gpodder to Bulgarian language :)

**Comment by sfbg** [comment]
> Nice!! Thanks for translating gpodder to Bulgarian language :)
Thanks! :)

I am noticing, though, that the Filter labels are not currently translatable because they are in a different repo: gpodder/gpodder-ui-qml

Ni idea how to fix that...

**Comment by carmenfdezb** [comment]
You are right ,I didn't notice that. I will take a look, thanks for this information!

**Comment by Keeper-of-the-Keys** [comment]
Yeah I'm not sure how much sense maintaining the split between the modules makes if this project is the only user of the other units.
OTOH like this it is easier for someone else to come in and build a QML gPodder application for some other platform.

**Comment by carmenfdezb** [comment]
> > Nice!! Thanks for translating gpodder to Bulgarian language :)
> > Thanks! :)
> 
> I am noticing, though, that the Filter labels are not currently translatable because they are in a different repo: gpodder/gpodder-ui-qml
> 
> Ni idea how to fix that...

Using lupdate_only in .pro file could be a solution, but this only works when I use lupdate manually, and it doesn't work when I build the app (it only searches inside qml\)

**Comment by carmenfdezb** [comment]
Finally I've added text filter to translate #74

**Pull request merged**
