### PR TITLE
App cover and player page improvements, part 2

### PR DESCRIPTION
**Pull request by sfbg**
Let's keep this one open until we agree that the design issues are aligned ans solved completely.

### CODE REVIEW

**Comment by sfbg** [comment]
I think it looks better now. Tell me what you think.

**Comment by carmenfdezb** [comment]
Hi @sfbg! It works fine to me. In my case, times are showed full in cover now, and it works properly when coverart in podcast is missing.

**Comment by carmenfdezb** [comment]
When sleep timer is actived, episode duration isn't showed in cover.
On the other hand, I get next warning while testing app in sdk:

`QML Column: Cannot specify top, bottom, verticalCenter, fill or centerIn anchors for items inside Column. Column will not function.`

In particular, there is anchor.top in lines 116 and 128 of PlayerCover.qml

**Comment by sfbg** [comment]
@carmenfdezb well the switch from full time to sleep timer was intentional. The idea is that if you have sleep timer, the idea is that this is the relevant information about the remaining running time. Do you think this line of thinking is OK.
The console error has to be fixed. I will look into it in the coming days.

**Comment by Keeper-of-the-Keys** [comment]
(Hope I'm not nit-picking)
Can we prevent information going into the button area?
Maybe have the times relative to the text of the title and not the picture? Or would that be ugly if it half overlaps the coverart?

**Comment by sfbg** [comment]
Definitely not nitpicking, I am not happy with the current state either, especially when the covers are small (3 in a row).
I do not think it will work visually having the time partly overlap with the coverart.

Unfortunately, I have little time in the next few weeks to dedicate time on this. I will try.

**Comment by Keeper-of-the-Keys** [comment]
Hi @sfbg would you prefer to merge as is and work on it again at some future time when you have time or leave this unmerged for now?

I'm hoping to create a few more PRs in the coming days of features for a new release and make a new release soon.

**Comment by sfbg** [comment]
Hi @Keeper-of-the-Keys , if it acceptable to you as it is currently, I do not mind merging it at all.
I definitely plan to work further on it, but realistically, I will not be able to do any work at least until the second week of November. So it might make sense.

**Comment by Keeper-of-the-Keys** [comment]
Merging... will do part part 3 when it becomes relevant.

**Pull request merged**
