### PR TITLE
Podcast "album art" added to Player page and cover...

### PR DESCRIPTION
**Pull request by sfbg**
...when podcasts are playing.
The App Cover design is "inspired" by the Jolla Media Player one.

### CODE REVIEW

**Comment by carmenfdezb** [comment]
Hi @sfbg, it looks really nice!!
 But I have two suggestions:
1) Podcast title and time in cover is too large, if they were a little smaller it would be perfect. In my case, I use other font and these texts aren't showed full.
2) IMHO, info about podcast should also be showed when a podcast is paused.

What do you think?

**Comment by sfbg** [comment]
@carmenfdezb thank you for the feedback and good ideas! This was the idea behind the PR, to discuss and refine it before merging.
1. Interesting effect with the custom font. As I said, I have taken over most of the design (and code) from the official music player. Could you please check if you have cropping issues there too? Concerning the episode name text, I'd prefer to keep it large with that gradient effect to the right, but reduce the fading. In your screenshot the full text is visible, it just fades too early. The cover is there to give an overview and i do not think it is super important to make sure that the full name od the episode is visible - for same podcasts it is a few sentences long, and that's too much.
Concerning the timers, I have made the size conditional based on episode length, so that it fits well, but with the custom font it is way off. I will consider ways to fix that, perhaps have two lines for progress and full running time.  
2. Generally agreed, but it should be tackled in a separate PR.

**Comment by carmenfdezb** [comment]
Yes, @sfbg, cover in official music player shows full text with custom font. Generally, the custom font that I use is smaller than the official one, so this issue is odd.
I agree, this can be fixed in other PR.

**Comment by Keeper-of-the-Keys** [comment]
Hey, thanks for the commit.
On my exisitng casts this is not working nicely, should I be updating something?

**Comment by Keeper-of-the-Keys** [comment]
I'm sorry my previous comment was way too vague, it's late :).

When player.podcast_coverart is undefined this the cover breaks not so nicely with the text of timepassed/total time superimposed on the name of the podcast title.

The lockscreen breaks elegantly as does the playerpage.

I'm not sure why all my podcasts fail though, as far as I know they (or at least some of them) do have coverart for their episodes.

**Comment by Keeper-of-the-Keys** [comment]
OK the reason they were undefined was I forgot to update submodules :blush: 
However the point of in-elegant failure does still stand.

Also from digging a bit in the db it seems that we don't currently have per-episode coverart as an option, we can probably add this however this should be in coordination with gpodder and possibly also with other projects that use our db format so we don't break compatibility...

@elelay

**Comment by Keeper-of-the-Keys** [comment]
FYI - a nice example of a podcast that has per episode artwork is FOAMFrat - 
http://foamfrat.libsyn.com/rss

I suspect that adding a coverart column to the PodcastEpisode is possible and would not break backwards for users or compatibility, however if we then also modify podcastparser to actually use this column that would break compatibility.

**Comment by carmenfdezb** [comment]
I see the same coverart for all episodes in http://foamfrat.libsyn.com/rss, I don't know a podcast with different coverart per episode.
I confirm that this feature doesn't work properly when the podcast doesn't have coverart.
On the other hand, I was thinking about times in cover: deleting spaces between times and '/' could solve my problem.

**Comment by Keeper-of-the-Keys** [comment]
Created https://github.com/gpodder/gpodder/issues/655 to discuss db changes.

**Comment by sfbg** [comment]
Thanks for the feedback! BTW, I would have kept the PR unmerged before we have solutions to all the small issues listed by you. Can the merge be reverted or is it too much hassle?
I will fix the problem with overlapping text when o cover art (or too small cover art) is available.
Also, will try to see how it looks like with no space between the times. Two lines is an interesting option too. I like the idea of bigger text on the cover when possible.
Concerning episode-specific coverart. To be honest, I am not sure it is a good idea to show it on the cover or player page. The cover art there is for the purpose of identifying which podcast you are listening to and most podcast do not have episode-specific coverart, so mixing these is problematic. I still think it would make sense to display it in the episode details. In that line, I am planning to make the episode details page reachable by taping on the cover art of in the Player page. What do you think?

**Comment by carmenfdezb** [comment]
> I see the same coverart for all episodes in http://foamfrat.libsyn.com/rss, I don't know a podcast with different coverart per episode.
@Keeper-of-the-Keys, I didn't understand you, so forget this comment. It's interesting to show the episode coverart if it is available.
@sfbg, I don't know how to revert a pull request easily, sorry for the inconveniences.

**Comment by elelay** [comment]
@carmenfdezb it should be possible to force-push master with the state before merge, but it is error prone (if somebody else just pushed something else it would disappear, also everybody having pulled the changed would have to force pull).
So better wait to be sure before merging -- not that it's a huge issue this time.

**Comment by Keeper-of-the-Keys** [comment]
I don't think it's worth the risk, we made a mistake we can live with it either way Jolla is still taking their time so we still have plenty of time to create another branch, fix and pull again :)

@sfbg Do you know if it's possible to show the times on the lockscreen? I was looking at the Mpris file in our source and didn't see anything exposed there but iirc the Jolla player does do it.

**Comment by sfbg** [comment]
I think I fixed the missing cover issue. Will create a new PR, but there are still open issues.
The official media player does not show the time on the lock screen by the way... So, nit sure it if it is possible.

**Pull request merged**
