### PR TITLE
Edit section

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
This adds the ability to edit the "section" of a podcast thus allowing to organize your podcasts a bit.

Go to the podcast details page and long click the section field to do this.

Your feedback before merging would be greatly appreciated @carmenfdezb  @sfbg

### CODE REVIEW

**Comment by carmenfdezb** [comment]
Nice!! I've tested and it works fine :)

**Comment by carmenfdezb** [comment]
Please, let me know when you will release next version, I would like to update Spanish translation.
Thanks for your great work!

**Comment by carmenfdezb** [comment]
Maybe short press is the best solution because only one menu is available, so it's more intuitive.

**Comment by Keeper-of-the-Keys** [comment]
OK added single click menu.

I notice that every time the sources change the build updates line numbers in the translation files, is there a better way to do this so that these files remain more static?

**Comment by carmenfdezb** [comment]
> I notice that every time the sources change the build updates line numbers in the translation files, is there a better way to do this so that these files remain more static?

Sorry, I don't know

**Pull request merged**
