### PR TITLE
Update harbour-org.gpodder.sailfish-zh_CN.ts

### PR DESCRIPTION
**Pull request by dashinfantry**

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
Hi @dashinfantry I fixed your original file and now it works (there were a few tags misplaced and a missing property), please note that a bunch of sentences were added you can find the latest version of the file with untranslated things here:
https://github.com/gpodder/gpodder-sailfish/pull/98/commits/d5ae66f7c4774b99fc053389524bb55cdd4a643c

**Comment by dashinfantry** [comment]
I can not edit it.Can you merge it first,then I will translation missing strings:)

**Comment by Keeper-of-the-Keys** [comment]
@dashinfantry done

**Comment by Keeper-of-the-Keys** [comment]
Close this in favor of PR#100?

**Comment by dashinfantry** [comment]
YES 星期一, 28 十月 2019, 03:54下午 +08:00 发件人 Keeper-of-the-Keys  notifications@github.com :

**Pull request closed without merging**
