### PR TITLE
Cover info: added cover stat when player is paused

### PR DESCRIPTION
**Pull request by carmenfdezb**

### CODE REVIEW

**Comment by carmenfdezb** [comment]
I've added cover stat when player is paused. Please, @Keeper-of-the-Keys and @sfbg, test it and comment here if you like this change.

**Comment by Keeper-of-the-Keys** [comment]
Hi @carmenfdezb sorry it's taken me a while to get to this, it looks very interesting I installed this on my phone will get back to you on what it's like for me in a few days :)

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb I like this but there is one change I would like - when the player finishes playing it should go back to only showing a reload icon or a reload and a play icon (to replay the last episode) but not the current situation where the buttons stay as if there is an episode playing.

**Comment by carmenfdezb** [comment]
Hi, @Keeper-of-the-Keys! When the episode has finished it is loaded in player. it's showed cover stat with 'play' and 'next cover' actions, if you click on next cover, cover stat is showed with 'previous cover' and 'sync' actions. So you all actions you want are available: play current episode and sync.
If I understand you, you only want to see one cover (cover stat), right?

**Comment by carmenfdezb** [comment]
I think the problem is that the episode is loaded in player when it's finished

**Comment by Keeper-of-the-Keys** [comment]
Hi @carmenfdezb this was how I solved it on the previous PR, should help you now too I think: https://github.com/gpodder/gpodder-sailfish/commit/17ed41e13e3d87f95c2fe9cba52d1674d3390b7a

**Comment by carmenfdezb** [comment]
Take a look my latest commit

**Comment by Keeper-of-the-Keys** [comment]
Hey @carmenfdezb merged, thanks and sorry it took a while.

Lets see how people like this.

**Pull request merged**
