### PR TITLE
Video indicator sailfish

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
For users to know easily whether the episode is video or audio.

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
Resolves https://github.com/gpodder/gpodder-sailfish/issues/57

**Comment by elelay** [comment]
Looks good, but it also contains #60. Let's wait until it's merge.

**Comment by Keeper-of-the-Keys** [comment]
Yeah, my mistake when creating a new branch I forgot to first switch back to master.
Screenshot:
Screenshot_20190706_001

**Comment by elelay** [comment]
Merged, thanks!

**Pull request merged**
