### PR TITLE
Translations support and Spanish language added

### PR DESCRIPTION
**Pull request by carmenfdezb**

### CODE REVIEW

**Comment by sfbg** [comment]
What for is the .qm file under /tranlations?

**Comment by carmenfdezb** [comment]
.qm file is needed to get the app translated to other languages. For example, harbour-org.gpodder.sailfish-es.qm is for the spanish language if your system language is Spanish.
You can use .ts file and QtLinguist to translate the app to other language and then, you must release it to .qm file.

**Comment by elelay** [comment]
@Keeper-of-the-keys what do you think about this?

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb is a respected SailfishOS community member who has contributed translations and other work to different projects, as far as I can tell the patch is OK, ideally we would do version number changes in a separate commit but considering the circumstances that seems to be OK for now.

**Comment by Keeper-of-the-Keys** [comment]
BTW @carmenfdezb are you interested in being more involved with gpodder-sailfish too?

**Comment by elelay** [comment]
OK. Great!
@carmenfdezb @Keeper-of-the-Keys feel free to fix the conflict and merge when you want.
Thanks,

**Comment by carmenfdezb** [comment]
> BTW @carmenfdezb are you interested in being more involved with gpodder-sailfish too?

Sorry for the late answer. Yes, of course!

**Pull request merged**
