### PR TITLE
Sdk build

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
This adds proper support for the Sailfish SDK.
Also updates the references to other projects.

Next update will remove MPRIS from the main branch to allow pushing to harbour.

@carmenfdezb can you please test? As far as I can tell nothing was broken, the add podcasts function from iTunes has stopped working but that probably needs backporting of updates from gpodder.

### CODE REVIEW

**Comment by elelay** [comment]
Nice!
AFAIK add podcast from iTunes is not in the gPodder 3 either.

**Comment by elelay** [comment]
Next thing is to setup a CI. Or does harbour provide one?

**Comment by elelay** [comment]
I think we should open a gpodderorg account on harbour, for gPodder sailfish team to share ownership. What do you think?

**Comment by carmenfdezb** [comment]
Hi @Keeper-of-the-Keys! I get an error when I try your 'sdk-build' branch, maybe I'm doing something wrong. I will take a look tomorrow.

**Comment by Keeper-of-the-Keys** [comment]
@elelay iTunes used to work and was kind of the only way I added since soundcloud did not work, but it seems that since they switched to podcasts.apple.com it stopped working, will need to look at that.\
CI - would be cool, I enrolled on harbour but haven't really checked it out yet.
gpodderorg account - may be good idea, though I am not a big fan of accounts that multiple people have access to instead of named accounts.

@carmenfdezb I just cloned it to my laptop with an outdated SDK and having issue with main.py missing from the RPM, will update SDK and see if that is the problem.

**Comment by Keeper-of-the-Keys** [comment]
Seems I pushed the wrong iteration of the spec file, I now succeeded in doing a clean build.
(Just make sure that when you pull you are also recursively pulling the updated sub-modules:
git clone --recursive [url]
git pull [remote] [branch] --recurse-submodules=yes
)

**Comment by elelay** [comment]
@Keeper-of-the-Keys as long as we can transfer or promote a new named account without breaking people's install I agree with you. Otherwise, we are in the situation we are now, were we all agree we want to carry it forward but maybe have to resubmit a *different app* only by name...

**Comment by carmenfdezb** [comment]
Thanks @Keeper-of-the-Keys! Now it's working!
I'm working to do enqueue option more visible in contextual menu, like this screenshot:
paint-17072019-193810

What do you think?

**Comment by Keeper-of-the-Keys** [comment]
Awesome, merging!
Considering I have so far not used the enqueue option possibly because it's not exposed well enough that is probably a good idea.
Though it may also be good to have a look at how many icons are there because that menu is getting very full.

**Pull request merged**
