### PR TITLE
OPML Import/Export support

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
Adds UI interface to OPML import/export functions, still needs https://github.com/gpodder/gpodder-ui-qml/pull/9 to merge and the subunit to be updated.

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb @sfbg 
Can you please test this
If all three open PRs work I intend to merge them tomorrow and if the merged result works fine make a new release next week (after merging all 3 PRs the translation files will need to be updated and a few other files)

**Comment by carmenfdezb** [comment]
Tested! Import opml option works fine but export opml doesn't work, it doesn't do anything when I try to export opml file.
Export option only works If I open gpodder from Terminal: export file is created inside the folder that I run command to start gpodder. Maybe it is needed to say in which folder create the opml file.

**Comment by Keeper-of-the-Keys** [comment]
In the emulator it creates it in ~/ unless a full path is provided by me.

Maybe the way it runs on the phone and on the emulator is different, I'll test that.

**Comment by Keeper-of-the-Keys** [comment]
The logs show a failure to create the file, I assume this is due to the path being used not being writable.

I'm going to prepend ~ to whatever is entered unless it contains '/' as a first char.

Also I guess it would be good if we could report an error back to the user if it can't write, will need to look at that too.

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb 
ATM I'm using the home directory path but others are available, documents, downloads etc.

https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-standardpaths.html/

**Comment by carmenfdezb** [comment]
Now it works :)
Only one suggestion: does it possible to filter *.opml files when selecting opml file to import?

**Comment by Keeper-of-the-Keys** [comment]
Added filter, I also allow it to show *.xml files just in case a user made such a file.

**Comment by Keeper-of-the-Keys** [comment]
Adding communication between the child and the parent to allow better user feedback of errors is a bigger project which I'm going to leave for a future version.

Unless there is some other things still missing/in need of improvement I intend to merge this.

**Comment by carmenfdezb** [comment]
Ok, merge all PR, everything works fine.
Thank you!

**Pull request merged**
