### PR TITLE
Update to Amber mpris

### PR DESCRIPTION
**Pull request by carmenfdezb**
It uses the new mpris module, and cover art is shown now in lockscreen:
Captura_20230305_001

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
Looks very good, this will break support for older phones no?
Maybe we can/should add an if(OS<4.5) around the import and keep both?

**Comment by carmenfdezb** [comment]
I think Amber.Mpris is available since sfos 4.4, but I'm not sure. OTH, org.nemomobile.mpris isn't available in a clean install of sfos 4.5

**Comment by Keeper-of-the-Keys** [comment]
I'm going to find my JP1 and test it on there, I suspect a tiny if/else around the import will be needed.

**Comment by Keeper-of-the-Keys** [comment]
I found my JP1, it was unable to install the rpm built with the new SDK, I suspect that previous released RPMs have also been uninstallable due to the same issue and nobody yelled so I'm merging this and will make a note in the release notes, if someone wants to build a package for older systems or tell me how I'm more than happy to still try and maintain support but for now this merges and breaks whatever it breaks.

**Pull request merged**
