### PR TITLE
Remove ui qml

### PR DESCRIPTION
**Pull request by Keeper-of-the-Keys**
Removes gpodder-ui-qml dependency

@thigg @sfbg @carmenfdezb as far as I can tell I did not break anything but I would like to hear other OKs before I merge.

@thigg once this is merged it would be great if you can rebase your PRs on this.

### CODE REVIEW

**Comment by carmenfdezb** [comment]
Hi @Keeper-of-the-Keys!
You have a pull request about fixed strings translation from old gpodder-ui-qml.
I think the rest of the code is ok

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb are you sure? The PR queue of gpodder-ui-qml is empty and there is no PR by you that was recently merged.
https://github.com/gpodder/gpodder-ui-qml/pulls?q=is%3Apr+is%3Aclosed

**Comment by Keeper-of-the-Keys** [comment]
Housekeeping - 
This PR closes #93

**Comment by carmenfdezb** [comment]
> @carmenfdezb are you sure? The PR queue of gpodder-ui-qml is empty and there is no PR by you that was recently merged.
> https://github.com/gpodder/gpodder-ui-qml/pulls?q=is%3Apr+is%3Aclosed

It is in your repo: Keeper-of-the-Keys:remove-ui-qml

**Comment by thigg** [comment]
What do you think about removing the GPodder prefix from the files?
Also the GPodderCore could be renamed to something like GPodderPyConnector. Core seems a bit odd to me here.

**Comment by thigg** [comment]
Also while at it, maybe it would be good to regroup the files.

Something like:

- model
  - EpisodeListModel, PodcastListModel, [Connections]
- view
  - AboutPage,SettingsPage,...
  - episodelist
    - EpisodeDetail(Page?), AllEpisodesPage, ...
  - player
  - podcasts
- core
  - GpodderCore

**Comment by Keeper-of-the-Keys** [comment]
> What do you think about removing the GPodder prefix from the files?
I don't see how that provides added value, we are still part of the gPodder project and these files map 1:1 to the reference implementation.

> Also the GPodderCore could be renamed to something like GPodderPyConnector. Core seems a bit odd to me here.
I guess that goes back to the fact that most of the python code lives in gpodder-core not sure how much it adds again.

**Comment by Keeper-of-the-Keys** [comment]
> Also while at it, maybe it would be good to regroup the files.
> 
> Something like (just a quick sketch):
> 
>     * model
>       
>       * EpisodeListModel, PodcastListModel, [Connections]
> 
>     * view
>       
>       * AboutPage,SettingsPage,...
>       * episodelist
>         
>         * EpisodeDetail(Page?), AllEpisodesPage, ...
>       * player
>       * podcasts
> 
>     * core
>       
>       * GpodderCore

Maybe for future but not in this PR, that is feature creep on PRs which makes them a mess and harder to review.

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb @thigg @sfbg if non of you found issues with this PR I will merge it tomorrow.

**Pull request merged**
