### PR TITLE
Enqueue option

### PR DESCRIPTION
**Pull request by carmenfdezb**
I've modified context menu and added enqueue option to do it more visible (instead of long press on play option):
enqueue

### CODE REVIEW

**Comment by carmenfdezb** [comment]
@Keeper-of-the-Keys , can you test it? I've tested in Jolla1 and XA2, and context menu is showed full.

**Comment by Keeper-of-the-Keys** [comment]
Hey @carmenfdezb great patch!
Tested it on my Xperia X running SFOS 3.1 (need to fire my old Jolla 1 up again too).
I'm not sure if the queue should be titled "player queue" "queue" or "enqueued", other then that fantastic!
One other thing - for code to display & align nice here it's probably best to set the SDK to use spaces for tabs (Tools > Options > Text Editor > Behavior > Tab Policy > "spaces only")

**Comment by Keeper-of-the-Keys** [comment]
This feature so far was not truly accesible in a meaningful way so you have now opened up a feature that is great for everyday use. :+1:  :)

**Comment by carmenfdezb** [comment]
Thanks for your advices! 
Finally I've changed 'Enqueue' for 'Queue', because page title is 'Player'.

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb I'm thinking of adding that you can see how long a podcast is somewhere, maybe either when you click and get the drop down line or some other way.

I think that if it gets added to the drop down then that menu will need to be expanded to 2 lines...

Any thoughts on the subject? Other ways of implementing it?

**Comment by carmenfdezb** [comment]
Nice idea!Maybe it can be added just below the podcast title, with smaller text size. What do you think?

**Comment by sfbg** [comment]
I am not sure the "Add to queue" icon is intuitive at all... Why  not the plus one: `icon-m-add`? 

The idea of showing the duration of the episode is nice, all to the right. Perhaps?

**Comment by carmenfdezb** [comment]
@sfbg, you are right, icon-m-add is more intuitive for "Add to queue" option. I will fix it.

**Comment by carmenfdezb** [comment]
> I am not sure the "Add to queue" icon is intuitive at all... Why not the plus one: `icon-m-add`?
> 
> The idea of showing the duration of the episode is nice, all to the right. Perhaps?

Done #71 #

**Pull request merged**
