### PR TITLE
[on hold] implemented a textsearchfilter for the episodelist

### LINKED ISSUE #42: [Feature request] podcast episode search
Hi!

I'd love to search for a specific podcast episode! Some times I have the need to re-listen to a specific one, but finding it is at the moment really hard. You have to scroll and you have only a few words at the beginning of the title and description to look at, and if the podcast library consists of literally hundreds of episodes, searching for that specific one.... It quickly gets REALLY tedious.

Could you just add a search field where one can quickly can specify which episodes to show in the list? E.g. something that does a "select * from episodes where title like '%somekeyword%';"....

Thanks!

### PR DESCRIPTION
**Pull request by thigg**
fixes #42 
is based on #137, thus the diff might be confusing. Can't select the PR as base.
Its all in 2b7f595

# In Action:
Peek 2020-09-20 00-53

### CODE REVIEW

**Comment by sfbg** [comment]
@thigg @Keeper-of-the-Keys tbh, I do not know if this feature is that useful. Especially as a dedicated filter. Perhaps search right in the episodes list, instead?

As I have mentioned elsewhere, filtering by pulling, then selecting is very cumbersome in my opinion.

**Comment by thigg** [comment]
Im not using the search very often. Because of that a permanent searchbar seems a bit like a waste of screenspace to me.

Having all the filters directly in the pulley do make the pulley very long (which might not be a problem, would have to try).
Also the "refresh podcasts"-item would be strange mixed up with the filters.

My personal workflow with the app is usually having the filtered episodelist open and refreshing the list about twice a day, thus having the refresh action easily accessible from the episodelist seems very practical to me.

Maybe we could put a toolbar on top/bottom which allows search/filter/updating in one element?
Maybe it could just be there where the current filter is now shown?

**Comment by thigg** [comment]
postponed until the other PRs are merged, leaving it open for now for reference. This needs to be rebased on the current master

**Comment by Keeper-of-the-Keys** [comment]
> @thigg @Keeper-of-the-Keys tbh, I do not know if this feature is that useful. Especially as a dedicated filter. Perhaps search right in the episodes list, instead?
> 
> As I have mentioned elsewhere, filtering by pulling, then selecting is very cumbersome in my opinion.

Text search would be cool, the exact UX we'll probably need to figure out and polish.

@thigg I'm closing this PR since it is too extensive to review in decent time, feel free to submit a cleaner PR that does only one feature.

**Pull request closed without merging**
