### PR TITLE
Show cover info when player is paused

### PR DESCRIPTION
**Pull request by carmenfdezb**

### CODE REVIEW

**Comment by Keeper-of-the-Keys** [comment]
@carmenfdezb Hey this has an unintended side effect on my phone that it never goes back to showing stats, does that also happen to you?

**Comment by carmenfdezb** [comment]
Yes, because you have an episode loaded in player (in pause). If you don't have any episode loaded in player you can see stats in cover.

**Comment by carmenfdezb** [comment]
For me is more useful to know what episode is loaded in player independently if player is playing or not. Maybe an option to clear player is needed.
Sorry for all the inconvenience, you can see the change I did, so you can revert my commit easily.

**Comment by Keeper-of-the-Keys** [comment]
OK I figured out what is going on, but a nice fix requires a change in gpodder-ui-qml, for now I'm hacking this in :man_shrugging:

**Comment by Keeper-of-the-Keys** [comment]
FYI this was the fix https://github.com/gpodder/gpodder-sailfish/commit/17ed41e13e3d87f95c2fe9cba52d1674d3390b7a
The cleaner fix is that I will probably add a property isPaused and isStopped to player.

**Comment by carmenfdezb** [comment]
Thank you @Keeper-of-the-Keys!! On the other hand, I made an icon cover action to skip forward in episode, what do you think:
Captura_20191210_001-m
In any case, we can decide here what actions could be available from cover, for example, if you want see stat in cover.

**Comment by carmenfdezb** [comment]
Furthermore, when player is paused it doesn't make sense the sync option from cover

**Comment by sfbg** [comment]
Fantastic Icon!

I would still like to have the sync icon if no show is playing. Perhaps in the place of the fast forward icon, but please not remove it.

**Comment by sfbg** [comment]
TBH, for me the optimal solution would be to still show the cover (perhaps much smaller, as a minature) and the stats at the same time, when no show is playing. I do not have a specific design, currently, though.

**Comment by carmenfdezb** [comment]
In that case, I think the best solution is to add an option jn settings to select cover actions

**Comment by Keeper-of-the-Keys** [comment]
I thought I was the only one who wanted to skip tracks from the cover?
Doing a decent settings interface would be a nice feature because then we can also allow people to set their own default filters etc.
There is a settings file but so I guess a first step would just be to allow editing the file and then figure out how to do settings the SFOS way (ie. allow people to do application settings through Settings > Apps > gPodder)

**Comment by Keeper-of-the-Keys** [comment]
@sfbg show stats superimposed on the coverart and no title/duration maybe?

**Comment by carmenfdezb** [comment]
> 
> 
> @sfbg show stats superimposed on the coverart and no title/duration maybe?

IMHO, it is too much info in a cover, and sorry but I don't undertand why info cover is differente if player is playing (player info) or is paused (stat info), when an episode is already loaded in player. Of course, I think stat info is very useful, but not If I'm using the player. I don't know what is the best solution here.





> I thought I was the only one who wanted to skip tracks from the cover?

I use mainly skip seconds in the same episode instead of skip tracks, but I understand that it is not the same preference for other users. This must be configured in Settings, but why not inside app?

**Comment by Keeper-of-the-Keys** [comment]
I like the stats a lot, I decide based on them if I can add another podcast subscription yet or not and atm they are only on the cover. For now I think wait and see if we get any positive/negative user feedback to decide how things should be (and get our own impressions from using it).

I have also been toying with the idea of showing stats in the podcast overview but we need to be careful that the UI doesn't turn into a mess as a result.

**Comment by carmenfdezb** [comment]
I've been thinking about this, and maybe this could be the solution:
Captura_01
Captura_02
What do you think?

**Comment by Keeper-of-the-Keys** [comment]
I think that looks like a very interesting concept :)

**Pull request merged**
