### PR TITLE
added italian translation

### PR DESCRIPTION
**Pull request by fravaccaro**

### CODE REVIEW

**Comment by carmenfdezb** [comment]
Thank you so much!

**Comment by fravaccaro** [comment]
My pleasure :) is there any plan for a release on OR?

**Comment by carmenfdezb** [comment]
Yes, we hope to release an updated version to harbour/open repos soon. @Keeper-of-the-Keys contacted to Jolla to migrate Store app to another count and we are waiting for an answer.

**Comment by fravaccaro** [comment]
I'm glad to hear that! Keep up the good work 💪

**Pull request merged**
